const DEFAULT_USER = {_id: '', name: '', email: ''}
const CLOUD_URL = 'https://api.nomoreparties.co';

const COLUMNS_AMOUNT_1000 = 4;
const COLUMNS_AMOUNT_800 = 3;
const COLUMNS_AMOUNT_500 = 2;
const COLUMNS_AMOUNT_NARROW = 1;

const START_LINE_AMOUNT_500 = 4;
const START_LINE_AMOUNT_NARROW = 5;

const MORE_LINE_AMOUNT_500 = 1;
const MORE_LINE_AMOUNT_NARROW = 2;

const SHORT_TIME = 45;

module.exports = {
  DEFAULT_USER,
  CLOUD_URL,

  COLUMNS_AMOUNT_1000,
  COLUMNS_AMOUNT_800,
  COLUMNS_AMOUNT_500,
  COLUMNS_AMOUNT_NARROW,

  START_LINE_AMOUNT_500,
  START_LINE_AMOUNT_NARROW,

  MORE_LINE_AMOUNT_500,
  MORE_LINE_AMOUNT_NARROW,

  SHORT_TIME,
}